// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf_AIly6sEqV3frh3-Ws_bwa3h_ORTwqc',
    appId: '1:863460254854:android:c21118ca13b817ca65dd07',
    messagingSenderId: '863460254854',
    projectId: 'chat-eb06c',
    storageBucket: 'chat-eb06c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVs5-YwqVC_OAS_dRUqbekmbQEp7QlT2Y',
    appId: '1:863460254854:ios:a7a837d11ca8937b65dd07',
    messagingSenderId: '863460254854',
    projectId: 'chat-eb06c',
    storageBucket: 'chat-eb06c.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8pIel2yWPLxRxJTm24hbAQR0jT5enjWg',
    appId: '1:863460254854:web:bcf485632a19b1a865dd07',
    messagingSenderId: '863460254854',
    projectId: 'chat-eb06c',
    authDomain: 'chat-eb06c.firebaseapp.com',
    storageBucket: 'chat-eb06c.firebasestorage.app',
    measurementId: 'G-X20DR015TW',
  );
}
